// frontend/src/Courses.jsx
import React, { useState, useEffect } from 'react';

const Courses = () => {
  const [courses, setCourses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchCourses = async () => {
      try {
        const response = await fetch('http://localhost:8000/courses');
        
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
        
        const data = await response.json();
        
        const coursesData = data.courses || data;
        
        if (!Array.isArray(coursesData)) {
          throw new Error("Invalid data format received from server");
        }
        
        setCourses(coursesData);
      } catch (err) {
        setError(err.message);
        console.error("Fetch error:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchCourses();
  }, []);

  if (loading) return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 to-purple-50 flex items-center justify-center">
      <div className="text-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-purple-600 mx-auto mb-4"></div>
        <p className="text-lg text-gray-700 font-medium">Loading courses...</p>
      </div>
    </div>
  );

  if (error) return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 to-purple-50 flex items-center justify-center">
      <div className="bg-white p-6 rounded-xl shadow-lg max-w-md mx-auto">
        <div className="text-red-500 mb-4">
          <svg className="w-12 h-12 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path>
          </svg>
        </div>
        <h2 className="text-xl font-bold text-gray-800 mb-2">Error Loading Courses</h2>
        <p className="text-gray-600 mb-4">{error}</p>
        <button 
          onClick={() => window.location.reload()}
          className="px-4 py-2 bg-gradient-to-r from-purple-600 to-indigo-600 text-white rounded-lg hover:from-purple-700 hover:to-indigo-700 transition"
        >
          Try Again
        </button>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 to-purple-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-6xl mx-auto">
        <div className="bg-white rounded-xl shadow-2xl overflow-hidden mb-8">
          <div className="bg-gradient-to-r from-purple-600 to-indigo-600 py-4 px-6">
            <h1 className="text-2xl font-bold text-white">Available Courses</h1>
            <p className="text-purple-100 text-sm mt-1">{courses.length} courses found</p>
          </div>
          
          <div className="p-6 overflow-x-auto">
            {courses.length > 0 ? (
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Field</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Duration</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Price</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {courses.map((course) => (
                    <tr key={course.course_id} className="hover:bg-gray-50 transition-colors duration-150">
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{course.course_id}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{course.course_name}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{course.course_field}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{course.course_duration}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-semibold text-purple-600">${course.course_price}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <div className="text-center py-12">
                <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                <h3 className="mt-2 text-lg font-medium text-gray-900">No courses available</h3>
                <p className="mt-1 text-sm text-gray-500">Check back later or add new courses.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Courses;

// admin/src/app/courses/courses.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';

@Component({
  selector: 'app-courses',
  standalone: false,
  templateUrl: './courses.component.html',
  styleUrl: './courses.component.css'
})
export class CoursesComponent {
   courses: any[] = [];
   successMessage: string = '';
   errorMessage: string = '';

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.loadCourses();
  }
  
  loadCourses(): void {
    this.http.get<any>('http://localhost:8000/courses').subscribe({
      next: (res) => {
        this.courses = res.courses;
        console.log(this.courses); 
      },
      error: (err) => {
        console.error('Error fetching courses:', err);
        this.errorMessage = 'Failed to load courses';
      }
    });
  }

  deleteCourse(courseId: number): void {
    if (confirm('Are you sure you want to delete this course?')) {
      this.http.post<any>('http://localhost:8000/delete_courses', { course_id: courseId }).subscribe({
        next: (res) => {
          console.log('Course deleted:', res);
          this.successMessage = 'Course has been deleted successfully';
          // Refresh the courses list
          this.loadCourses();
          
          // Clear success message after 3 seconds
          setTimeout(() => {
            this.successMessage = '';
          }, 3000);
        },
        error: (err) => {
          console.error('Error deleting course:', err);
          this.errorMessage = `Error deleting course: ${err.error?.detail || 'Unknown error'}`;
          
          // Clear error message after 3 seconds
          setTimeout(() => {
            this.errorMessage = '';
          }, 3000);
        }
      });
    }
  }
}

<div class="min-h-screen bg-gradient-to-br from-indigo-50 to-purple-50 py-8 px-4 sm:px-6 lg:px-8">  <div class="max-w-7xl mx-auto">
    <!-- Simple notification messages -->
    <div *ngIf="successMessage" class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded-lg mb-4 flex justify-between items-center">
      <span>{{ successMessage }}</span>
      <button (click)="successMessage = ''" class="text-green-700 hover:text-green-900">
        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
    
    <div *ngIf="errorMessage" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-lg mb-4 flex justify-between items-center">
      <span>{{ errorMessage }}</span>
      <button (click)="errorMessage = ''" class="text-red-700 hover:text-red-900">
        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
    
    <div class="bg-white rounded-xl shadow-xl overflow-hidden mb-6">
      <div class="bg-gradient-to-r from-purple-600 to-indigo-600 py-4 px-6">
        <h2 class="text-2xl font-bold text-white">Available Courses</h2>
        <p class="text-purple-100 text-sm mt-1">Browse our selection of courses</p>
      </div>
    </div>
    
    <!-- No courses message -->
    <div *ngIf="courses.length === 0" class="bg-white rounded-xl shadow-lg p-8 text-center">
      <svg class="h-16 w-16 text-purple-400 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
      </svg>
      <p class="text-lg text-gray-600">No courses found. 🫥</p>
    </div>
    
    <!-- Course grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div *ngFor="let course of courses" class="bg-white rounded-xl shadow-lg overflow-hidden transform transition-all duration-300 hover:scale-[1.02] hover:shadow-2xl">        <!-- Course header -->
        <div class="bg-gradient-to-r from-purple-600 to-indigo-600 py-3 px-4 text-white">
          <h3 class="text-xl font-bold">{{ course.course_name }}</h3>
          <p class="text-purple-100 text-sm">{{ course.course_field }}</p>
          <!-- Debug: Display course ID -->
          <p class="text-purple-100 text-xs mt-1">ID: {{ course.course_id }}</p>
        </div>
        
        <!-- Course content -->
        <div class="p-6 space-y-4">
          <div class="flex items-center">
            <svg class="h-5 w-5 text-purple-500 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <p><span class="font-medium text-gray-700">Duration:</span> <span class="text-gray-600">{{ course.course_duration }}</span></p>
          </div>
          
          <div class="flex items-center">
            <svg class="h-5 w-5 text-purple-500 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <p><span class="font-medium text-gray-700">Price:</span> <span class="text-gray-600">${{ course.course_price }}</span></p>
          </div>
            <div class="flex items-center">
            <svg class="h-5 w-5 text-purple-500 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
            </svg>            <p><span class="font-medium text-gray-700">Field:</span> <span class="text-gray-600">{{ course.course_field }}</span></p>
          </div>          <!-- Simple delete button -->
          <div class="mt-4 pt-3 border-t border-gray-100">
            <button 
              (click)="deleteCourse(course.course_id)" 
              class="w-full py-2 bg-red-500 hover:bg-red-600 text-white rounded-md flex items-center justify-center transition-colors duration-300">
              <svg class="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
              Delete Course
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
